name: moviepass
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  get: 4.6.6
  searchfield: 0.8.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: 2.0.3
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
  fonts:
    - family: Jost
      fonts:
        - asset: assets/fonts/Jost-Regular.ttf
        - asset: assets/fonts/Jost-Italic.ttf
          style: italic
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
  uses-material-design: true
